# Generated by Django 5.1.15 on 2026-08-30 20:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('scans', '0001_initial'),
        ('sites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SafetyIncident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('incident_type', models.CharField(choices=[('gas_threshold', 'Gas Threshold'), ('structural_instability', 'Structural Instability'), ('slope_failure', 'Slope Failure'), ('equipment', 'Equipment'), ('proximity_breach', 'Proximity Breach'), ('environmental', 'Environmental'), ('other', 'Other')], max_length=30)),
                ('risk_score', models.PositiveSmallIntegerField(default=0)),
                ('sensor_readings', models.JSONField(blank=True, default=dict)),
                ('gps_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('gps_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved'), ('escalated', 'Escalated')], default='open', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='safety_incidents_acknowledged', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safety_incidents', to='accounts.organisation')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='safety_incidents_reported', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safety_incidents', to='sites.site')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='safety_incidents', to='scans.mineralzone')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
