# Generated by Django 5.1.15 on 2026-08-30 20:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('framework', models.CharField(choices=[('oecd', 'OECD Due Diligence'), ('itsci', 'ITSCI'), ('rmb', 'RMB Licensing'), ('eu', 'EU Conflict Minerals')], max_length=10)),
                ('period', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('overdue', 'Overdue')], default='draft', max_length=12)),
                ('coverage_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('flagged_lots', models.PositiveIntegerField(default=0)),
                ('submitted_to', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_reports', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_reports', to='accounts.organisation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
