# Generated by Django 5.1.15 on 2026-08-30 20:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('sites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MineralBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('coc_id', models.CharField(max_length=64, unique=True)),
                ('mineral_type', models.CharField(max_length=20)),
                ('origin_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('origin_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('extraction_timestamp', models.DateTimeField(blank=True, null=True)),
                ('weight_kg', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('grade_detected', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('grade_confirmed', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('status', models.CharField(choices=[('scanned', 'Scanned'), ('weighed', 'Weighed'), ('graded', 'Graded'), ('in_storage', 'In Storage'), ('in_transit', 'In Transit'), ('at_processing', 'At Processing'), ('exported', 'Exported'), ('rejected', 'Rejected')], default='scanned', max_length=20)),
                ('qr_code_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches_created', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mineral_batches', to='accounts.organisation')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mineral_batches', to='sites.site')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustodyEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('extraction', 'Extraction'), ('weigh_in', 'Weigh-in'), ('storage_in', 'Storage'), ('dispatch', 'Dispatch'), ('waypoint', 'Waypoint'), ('receipt', 'Receipt'), ('processing', 'Processing'), ('export', 'Export'), ('rejection', 'Rejection')], max_length=20)),
                ('from_party', models.CharField(blank=True, max_length=255)),
                ('to_party', models.CharField(blank=True, max_length=255)),
                ('gps_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('gps_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('quantity_kg', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('authorised_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custody_events_authorised', to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='traceability.mineralbatch')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
