"""incident history and resolution

Revision ID: 11b3c856c018
Revises: fc552200c54f
Create Date: 2026-09-28 22:42:13.761014

"""
from typing import Sequence, Union

import uuid

from alembic import op
import sqlalchemy as sa
import app.types  # needed for the custom GUID type used on every PK/FK


# revision identifiers, used by Alembic.
revision: str = '11b3c856c018'
down_revision: Union[str, None] = 'fc552200c54f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incident_events',
    sa.Column('id', app.types.GUID(), nullable=False),
    sa.Column('incident_id', app.types.GUID(), nullable=False),
    sa.Column('event_type', sa.String(length=12), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('actor_id', app.types.GUID(), nullable=True),
    sa.Column('actor_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['incident_id'], ['safety_incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_incident_events_incident_created', 'incident_events', ['incident_id', 'created_at'], unique=False)
    op.add_column('safety_incidents', sa.Column('resolved_by_id', app.types.GUID(), nullable=True))
    op.add_column('safety_incidents', sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key('fk_safety_incidents_resolved_by_id', 'safety_incidents', 'users', ['resolved_by_id'], ['id'], ondelete='SET NULL')

    # Backfill history for incidents that predate it, from what the incident
    # row itself records, so no timeline starts empty.
    bind = op.get_bind()
    incidents = sa.table(
        'safety_incidents',
        sa.column('id', app.types.GUID()), sa.column('status', sa.String()),
        sa.column('reported_by_id', app.types.GUID()), sa.column('acknowledged_by_id', app.types.GUID()),
        sa.column('acknowledged_at', sa.DateTime(timezone=True)), sa.column('created_at', sa.DateTime(timezone=True)),
        sa.column('description', sa.Text()),
    )
    users = sa.table('users', sa.column('id', app.types.GUID()), sa.column('full_name', sa.String()))
    events = sa.table(
        'incident_events',
        sa.column('id', app.types.GUID()), sa.column('incident_id', app.types.GUID()),
        sa.column('event_type', sa.String()), sa.column('note', sa.Text()),
        sa.column('actor_id', app.types.GUID()), sa.column('actor_name', sa.String()),
        sa.column('created_at', sa.DateTime(timezone=True)),
    )
    names = {r.id: r.full_name for r in bind.execute(sa.select(users.c.id, users.c.full_name))}
    rows = []
    for inc in bind.execute(sa.select(incidents)):
        def ev(kind, actor, at, note=''):
            rows.append(dict(id=uuid.uuid4(), incident_id=inc.id, event_type=kind, note=note, actor_id=actor,
                             actor_name=names.get(actor, ''), created_at=at))
        ev('reported', inc.reported_by_id, inc.created_at, inc.description or '')
        if inc.acknowledged_at is not None:
            ev('acknowledged', inc.acknowledged_by_id, inc.acknowledged_at)
        if inc.status == 'resolved':
            ev('resolved', None, inc.acknowledged_at or inc.created_at, 'Resolved before incident history was tracked.')
        elif inc.status == 'escalated':
            ev('escalated', None, inc.acknowledged_at or inc.created_at, 'Escalated before incident history was tracked.')
    if rows:
        op.bulk_insert(events, rows)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_safety_incidents_resolved_by_id', 'safety_incidents', type_='foreignkey')
    op.drop_column('safety_incidents', 'resolved_at')
    op.drop_column('safety_incidents', 'resolved_by_id')
    op.drop_index('ix_incident_events_incident_created', table_name='incident_events')
    op.drop_table('incident_events')
    # ### end Alembic commands ###
