"""initial schema

Revision ID: 2e34ebd5bda1
Revises: 
Create Date: 2026-08-31 14:20:34.895681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.types


# revision identifiers, used by Alembic.
revision: str = '2e34ebd5bda1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organisations',
    sa.Column('id', app.types.GUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('registration_number', sa.String(length=100), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('license_tier', sa.String(length=50), nullable=False),
    sa.Column('primary_contact_email', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organisations_slug'), 'organisations', ['slug'], unique=True)
    op.create_table('sites',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('organisation_id', app.types.GUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('lat', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('lng', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('primary_mineral', sa.String(length=20), nullable=False),
    sa.Column('secondary_minerals', sa.JSON(), nullable=False),
    sa.Column('grade_pct', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('estimated_tonnage', sa.Integer(), nullable=False),
    sa.Column('safety_score', sa.Integer(), nullable=False),
    sa.Column('risk_level', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('last_scan', sa.DateTime(timezone=True), nullable=True),
    sa.Column('depth_meters', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', app.types.GUID(), nullable=False),
    sa.Column('organisation_id', app.types.GUID(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_staff', sa.Boolean(), nullable=False),
    sa.Column('is_email_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('compliance_reports',
    sa.Column('id', app.types.GUID(), nullable=False),
    sa.Column('organisation_id', app.types.GUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('framework', sa.String(length=10), nullable=False),
    sa.Column('period', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('coverage_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('flagged_lots', sa.Integer(), nullable=False),
    sa.Column('submitted_to', sa.String(length=255), nullable=False),
    sa.Column('generated_by_id', app.types.GUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['generated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mineral_batches',
    sa.Column('id', app.types.GUID(), nullable=False),
    sa.Column('coc_id', sa.String(length=64), nullable=False),
    sa.Column('organisation_id', app.types.GUID(), nullable=False),
    sa.Column('site_id', sa.String(length=32), nullable=False),
    sa.Column('mineral_type', sa.String(length=20), nullable=False),
    sa.Column('origin_lat', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('origin_lng', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('extraction_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('weight_kg', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('grade_detected', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('grade_confirmed', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('qr_code_url', sa.String(length=500), nullable=False),
    sa.Column('created_by_id', app.types.GUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mineral_batches_coc_id'), 'mineral_batches', ['coc_id'], unique=True)
    op.create_table('scan_sessions',
    sa.Column('id', app.types.GUID(), nullable=False),
    sa.Column('organisation_id', app.types.GUID(), nullable=False),
    sa.Column('site_id', sa.String(length=32), nullable=False),
    sa.Column('operator_id', app.types.GUID(), nullable=True),
    sa.Column('sensor_types', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['operator_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('custody_events',
    sa.Column('id', app.types.GUID(), nullable=False),
    sa.Column('batch_id', app.types.GUID(), nullable=False),
    sa.Column('event_type', sa.String(length=20), nullable=False),
    sa.Column('from_party', sa.String(length=255), nullable=False),
    sa.Column('to_party', sa.String(length=255), nullable=False),
    sa.Column('gps_lat', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('gps_lng', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('quantity_kg', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('authorised_by_id', app.types.GUID(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['authorised_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['batch_id'], ['mineral_batches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mineral_zones',
    sa.Column('id', app.types.GUID(), nullable=False),
    sa.Column('scan_session_id', app.types.GUID(), nullable=False),
    sa.Column('organisation_id', app.types.GUID(), nullable=False),
    sa.Column('mineral_type', sa.String(length=20), nullable=False),
    sa.Column('confidence_score', sa.Integer(), nullable=False),
    sa.Column('estimated_depth_m', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('estimated_tonnage', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('flagged_anomaly', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scan_session_id'], ['scan_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shipments',
    sa.Column('id', app.types.GUID(), nullable=False),
    sa.Column('organisation_id', app.types.GUID(), nullable=False),
    sa.Column('batch_id', app.types.GUID(), nullable=True),
    sa.Column('origin_name', sa.String(length=255), nullable=False),
    sa.Column('origin_lat', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('origin_lng', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('destination_name', sa.String(length=255), nullable=False),
    sa.Column('destination_lat', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('destination_lng', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('driver', sa.String(length=255), nullable=False),
    sa.Column('vehicle', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('progress_pct', sa.Integer(), nullable=False),
    sa.Column('eta_hours', sa.Numeric(precision=6, scale=1), nullable=False),
    sa.Column('weight_kg', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('gps_integrity', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['mineral_batches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('safety_incidents',
    sa.Column('id', app.types.GUID(), nullable=False),
    sa.Column('organisation_id', app.types.GUID(), nullable=False),
    sa.Column('site_id', sa.String(length=32), nullable=False),
    sa.Column('zone_id', app.types.GUID(), nullable=True),
    sa.Column('incident_type', sa.String(length=30), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('sensor_readings', sa.JSON(), nullable=False),
    sa.Column('gps_lat', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('gps_lng', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('reported_by_id', app.types.GUID(), nullable=True),
    sa.Column('acknowledged_by_id', app.types.GUID(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['acknowledged_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reported_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['zone_id'], ['mineral_zones.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('safety_incidents')
    op.drop_table('shipments')
    op.drop_table('mineral_zones')
    op.drop_table('custody_events')
    op.drop_table('scan_sessions')
    op.drop_index(op.f('ix_mineral_batches_coc_id'), table_name='mineral_batches')
    op.drop_table('mineral_batches')
    op.drop_table('compliance_reports')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('sites')
    op.drop_index(op.f('ix_organisations_slug'), table_name='organisations')
    op.drop_table('organisations')
    # ### end Alembic commands ###
