"""add shipment mineral type

Revision ID: 489be7138c04
Revises: 4c502050054d
Create Date: 2026-09-14 12:27:14.494954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.types  # needed for the custom GUID type used on every PK/FK


# revision identifiers, used by Alembic.
revision: str = '489be7138c04'
down_revision: Union[str, None] = '4c502050054d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default required: existing rows must satisfy NOT NULL on add.
    op.add_column(
        'shipments',
        sa.Column('mineral_type', sa.String(length=20), nullable=False, server_default=''),
    )
    op.alter_column('shipments', 'mineral_type', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shipments', 'mineral_type')
    # ### end Alembic commands ###
