"""add mineral batch compliant flag

Revision ID: 4c502050054d
Revises: cf869ba29c3d
Create Date: 2026-09-14 12:17:58.154088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.types  # needed for the custom GUID type used on every PK/FK


# revision identifiers, used by Alembic.
revision: str = '4c502050054d'
down_revision: Union[str, None] = 'cf869ba29c3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default required: existing rows must satisfy NOT NULL on add.
    op.add_column(
        'mineral_batches',
        sa.Column('compliant', sa.Boolean(), nullable=False, server_default=sa.true()),
    )
    op.alter_column('mineral_batches', 'compliant', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mineral_batches', 'compliant')
    # ### end Alembic commands ###
