"""add mineral zone classification detail fields

Revision ID: b2dfb661cdc1
Revises: e69c7d763730
Create Date: 2026-09-14 13:00:41.082095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.types  # needed for the custom GUID type used on every PK/FK


# revision identifiers, used by Alembic.
revision: str = 'b2dfb661cdc1'
down_revision: Union[str, None] = 'e69c7d763730'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default required: existing rows must satisfy NOT NULL on add.
    op.add_column(
        'mineral_zones',
        sa.Column('confidence_alternatives', sa.JSON(), nullable=False, server_default=sa.text("'[]'::json")),
    )
    op.alter_column('mineral_zones', 'confidence_alternatives', server_default=None)
    op.add_column('mineral_zones', sa.Column('grade_pct', sa.Numeric(precision=6, scale=2), nullable=True))
    op.add_column('mineral_zones', sa.Column('area_ha', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mineral_zones', 'area_ha')
    op.drop_column('mineral_zones', 'grade_pct')
    op.drop_column('mineral_zones', 'confidence_alternatives')
    # ### end Alembic commands ###
