"""add ml classification fields to scans

Revision ID: b9cfac4615c8
Revises: b2dfb661cdc1
Create Date: 2026-09-28 22:14:00.686319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.types  # needed for the custom GUID type used on every PK/FK


# revision identifiers, used by Alembic.
revision: str = 'b9cfac4615c8'
# dev's migration chain is missing 2734f18d37ed (audit logs) and
# fc552200c54f (fleet registry) — both only merged to main — so this
# revises dev's actual head, b2dfb661cdc1, not main's.
down_revision: Union[str, None] = 'b2dfb661cdc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mineral_zones', sa.Column('model_version', sa.String(length=20), nullable=True))
    op.add_column('scan_sessions', sa.Column('raw_reading', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scan_sessions', 'raw_reading')
    op.drop_column('mineral_zones', 'model_version')
    # ### end Alembic commands ###
