"""sensor ingestion devices readings and safety rules

Revision ID: bc12e5bf5308
Revises: 2b6a645aeddc
Create Date: 2026-09-29 10:34:09.308928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.types  # needed for the custom GUID type used on every PK/FK


# revision identifiers, used by Alembic.
revision: str = 'bc12e5bf5308'
down_revision: Union[str, None] = '2b6a645aeddc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('safety_rules',
    sa.Column('id', app.types.GUID(), nullable=False),
    sa.Column('organisation_id', app.types.GUID(), nullable=False),
    sa.Column('site_id', sa.String(length=32), nullable=True),
    sa.Column('metric', sa.String(length=40), nullable=False),
    sa.Column('comparator', sa.String(length=2), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('incident_type', sa.String(length=30), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_safety_rules_organisation_id'), 'safety_rules', ['organisation_id'], unique=False)
    op.create_table('sensor_devices',
    sa.Column('id', app.types.GUID(), nullable=False),
    sa.Column('organisation_id', app.types.GUID(), nullable=False),
    sa.Column('site_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('sensor_type', sa.String(length=20), nullable=False),
    sa.Column('api_key_hash', sa.String(length=64), nullable=False),
    sa.Column('api_key_prefix', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_values', sa.JSON(), nullable=False),
    sa.Column('created_by_id', app.types.GUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_key_hash')
    )
    op.create_index(op.f('ix_sensor_devices_organisation_id'), 'sensor_devices', ['organisation_id'], unique=False)
    op.create_table('sensor_files',
    sa.Column('id', app.types.GUID(), nullable=False),
    sa.Column('organisation_id', app.types.GUID(), nullable=False),
    sa.Column('site_id', sa.String(length=32), nullable=False),
    sa.Column('scan_session_id', app.types.GUID(), nullable=True),
    sa.Column('sensor_type', sa.String(length=20), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('file_kind', sa.String(length=12), nullable=True),
    sa.Column('storage_key', sa.String(length=500), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('bbox', sa.JSON(), nullable=True),
    sa.Column('file_metadata', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('validation_errors', sa.JSON(), nullable=False),
    sa.Column('validation_warnings', sa.JSON(), nullable=False),
    sa.Column('upload_method', sa.String(length=8), nullable=False),
    sa.Column('uploaded_by_id', app.types.GUID(), nullable=True),
    sa.Column('device_id', app.types.GUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['sensor_devices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scan_session_id'], ['scan_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sensor_files_org_created', 'sensor_files', ['organisation_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_sensor_files_scan_session_id'), 'sensor_files', ['scan_session_id'], unique=False)
    op.create_table('sensor_readings',
    sa.Column('id', app.types.GUID(), nullable=False),
    sa.Column('organisation_id', app.types.GUID(), nullable=False),
    sa.Column('device_id', app.types.GUID(), nullable=False),
    sa.Column('site_id', sa.String(length=32), nullable=False),
    sa.Column('sensor_type', sa.String(length=20), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lat', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('lng', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('values', sa.JSON(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['sensor_devices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sensor_readings_device_recorded', 'sensor_readings', ['device_id', 'recorded_at'], unique=False)
    op.create_index('ix_sensor_readings_site_recorded', 'sensor_readings', ['site_id', 'recorded_at'], unique=False)
    op.add_column('safety_incidents', sa.Column('source_device_id', app.types.GUID(), nullable=True))
    op.add_column('safety_incidents', sa.Column('rule_id', app.types.GUID(), nullable=True))
    op.add_column('safety_incidents', sa.Column('source_label', sa.String(length=255), nullable=False, server_default=''))
    op.create_foreign_key('fk_safety_incidents_source_device_id', 'safety_incidents', 'sensor_devices', ['source_device_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_safety_incidents_rule_id', 'safety_incidents', 'safety_rules', ['rule_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_safety_incidents_rule_id', 'safety_incidents', type_='foreignkey')
    op.drop_constraint('fk_safety_incidents_source_device_id', 'safety_incidents', type_='foreignkey')
    op.drop_column('safety_incidents', 'source_label')
    op.drop_column('safety_incidents', 'rule_id')
    op.drop_column('safety_incidents', 'source_device_id')
    op.drop_index('ix_sensor_readings_site_recorded', table_name='sensor_readings')
    op.drop_index('ix_sensor_readings_device_recorded', table_name='sensor_readings')
    op.drop_table('sensor_readings')
    op.drop_index(op.f('ix_sensor_files_scan_session_id'), table_name='sensor_files')
    op.drop_index('ix_sensor_files_org_created', table_name='sensor_files')
    op.drop_table('sensor_files')
    op.drop_index(op.f('ix_sensor_devices_organisation_id'), table_name='sensor_devices')
    op.drop_table('sensor_devices')
    op.drop_index(op.f('ix_safety_rules_organisation_id'), table_name='safety_rules')
    op.drop_table('safety_rules')
    # ### end Alembic commands ###
