"""add site last_scan_method

Revision ID: cf869ba29c3d
Revises: 7a1f3c9de2b4
Create Date: 2026-09-14 11:57:19.363175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.types  # needed for the custom GUID type used on every PK/FK


# revision identifiers, used by Alembic.
revision: str = 'cf869ba29c3d'
down_revision: Union[str, None] = '7a1f3c9de2b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default required: existing rows must satisfy NOT NULL on add.
    op.add_column(
        'sites',
        sa.Column('last_scan_method', sa.String(length=50), nullable=False, server_default=''),
    )
    op.alter_column('sites', 'last_scan_method', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sites', 'last_scan_method')
    # ### end Alembic commands ###
