"""add batch compliance note and custody event flagged

Revision ID: e69c7d763730
Revises: 489be7138c04
Create Date: 2026-09-14 12:40:12.039390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.types  # needed for the custom GUID type used on every PK/FK


# revision identifiers, used by Alembic.
revision: str = 'e69c7d763730'
down_revision: Union[str, None] = '489be7138c04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default required: existing rows must satisfy NOT NULL on add.
    op.add_column(
        'custody_events',
        sa.Column('flagged', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.alter_column('custody_events', 'flagged', server_default=None)
    op.add_column(
        'mineral_batches',
        sa.Column('compliance_note', sa.Text(), nullable=False, server_default=''),
    )
    op.alter_column('mineral_batches', 'compliance_note', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mineral_batches', 'compliance_note')
    op.drop_column('custody_events', 'flagged')
    # ### end Alembic commands ###
