"""fleet registry and shipment tracking

Revision ID: fc552200c54f
Revises: 2734f18d37ed
Create Date: 2026-09-27 12:39:01.699751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.types  # needed for the custom GUID type used on every PK/FK


# revision identifiers, used by Alembic.
revision: str = 'fc552200c54f'
down_revision: Union[str, None] = '2734f18d37ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drivers',
    sa.Column('id', app.types.GUID(), nullable=False),
    sa.Column('organisation_id', app.types.GUID(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('license_no', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drivers_organisation_id'), 'drivers', ['organisation_id'], unique=False)
    op.create_table('vehicles',
    sa.Column('id', app.types.GUID(), nullable=False),
    sa.Column('organisation_id', app.types.GUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('plate', sa.String(length=20), nullable=False),
    sa.Column('vehicle_type', sa.String(length=12), nullable=False),
    sa.Column('capacity_kg', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicles_organisation_id'), 'vehicles', ['organisation_id'], unique=False)
    op.create_table('shipment_events',
    sa.Column('id', app.types.GUID(), nullable=False),
    sa.Column('shipment_id', app.types.GUID(), nullable=False),
    sa.Column('event_type', sa.String(length=12), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('actor_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_shipment_events_shipment_created', 'shipment_events', ['shipment_id', 'created_at'], unique=False)
    op.create_table('shipment_pings',
    sa.Column('id', app.types.GUID(), nullable=False),
    sa.Column('shipment_id', app.types.GUID(), nullable=False),
    sa.Column('lat', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('lng', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('speed_kmh', sa.Numeric(precision=6, scale=1), nullable=True),
    sa.Column('source', sa.String(length=10), nullable=False),
    sa.Column('recorded_by_id', app.types.GUID(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recorded_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_shipment_pings_shipment_recorded', 'shipment_pings', ['shipment_id', 'recorded_at'], unique=False)
    op.add_column('shipments', sa.Column('reference', sa.String(length=32), nullable=True))
    op.add_column('shipments', sa.Column('vehicle_id', app.types.GUID(), nullable=True))
    op.add_column('shipments', sa.Column('driver_id', app.types.GUID(), nullable=True))
    op.add_column('shipments', sa.Column('departed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('shipments', sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('shipments', sa.Column('last_ping_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('shipments', sa.Column('last_lat', sa.Numeric(precision=9, scale=6), nullable=True))
    op.add_column('shipments', sa.Column('last_lng', sa.Numeric(precision=9, scale=6), nullable=True))
    op.create_unique_constraint('uq_shipments_reference', 'shipments', ['reference'])
    op.create_foreign_key('fk_shipments_vehicle_id', 'shipments', 'vehicles', ['vehicle_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_shipments_driver_id', 'shipments', 'drivers', ['driver_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_shipments_driver_id', 'shipments', type_='foreignkey')
    op.drop_constraint('fk_shipments_vehicle_id', 'shipments', type_='foreignkey')
    op.drop_constraint('uq_shipments_reference', 'shipments', type_='unique')
    op.drop_column('shipments', 'last_lng')
    op.drop_column('shipments', 'last_lat')
    op.drop_column('shipments', 'last_ping_at')
    op.drop_column('shipments', 'delivered_at')
    op.drop_column('shipments', 'departed_at')
    op.drop_column('shipments', 'driver_id')
    op.drop_column('shipments', 'vehicle_id')
    op.drop_column('shipments', 'reference')
    op.drop_index('ix_shipment_pings_shipment_recorded', table_name='shipment_pings')
    op.drop_table('shipment_pings')
    op.drop_index('ix_shipment_events_shipment_created', table_name='shipment_events')
    op.drop_table('shipment_events')
    op.drop_index(op.f('ix_vehicles_organisation_id'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index(op.f('ix_drivers_organisation_id'), table_name='drivers')
    op.drop_table('drivers')
    # ### end Alembic commands ###
