# Generated by Django 5.1.15 on 2026-08-30 20:28

import accounts.managers
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('registration_number', models.CharField(blank=True, max_length=100)),
                ('country_code', models.CharField(choices=[('RW', 'Rwanda'), ('CD', 'DR Congo'), ('UG', 'Uganda'), ('TZ', 'Tanzania'), ('KE', 'Kenya'), ('BI', 'Burundi')], default='RW', max_length=2)),
                ('license_tier', models.CharField(default='trial', max_length=50)),
                ('primary_contact_email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('field_operator', 'Field Operator'), ('drone_operator', 'Drone Operator'), ('geologist', 'Geologist'), ('mine_manager', 'Mine Manager'), ('safety_officer', 'Safety Officer'), ('compliance_manager', 'Compliance Manager'), ('government_auditor', 'Government Auditor'), ('investor', 'Investor'), ('company_admin', 'Company Admin'), ('system_admin', 'System Admin')], default='field_operator', max_length=32)),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='accounts.organisation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', accounts.managers.UserManager()),
            ],
        ),
    ]
