# Generated by Django 5.1.15 on 2026-08-30 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('country_code', models.CharField(default='RW', max_length=2)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('primary_mineral', models.CharField(choices=[('cassiterite', 'Cassiterite'), ('coltan', 'Coltan'), ('wolframite', 'Wolframite'), ('gold', 'Gold'), ('beryl', 'Beryl'), ('lithium', 'Lithium'), ('cobalt', 'Cobalt'), ('copper', 'Copper'), ('gemstone', 'Gemstone'), ('unknown', 'Unknown')], max_length=20)),
                ('secondary_minerals', models.JSONField(blank=True, default=list)),
                ('grade_pct', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('confidence', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('estimated_tonnage', models.BigIntegerField(default=0)),
                ('safety_score', models.PositiveSmallIntegerField(default=0)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('surveying', 'Surveying'), ('flagged', 'Flagged'), ('depleted', 'Depleted')], default='active', max_length=12)),
                ('last_scan', models.DateTimeField(blank=True, null=True)),
                ('depth_meters', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='accounts.organisation')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
