# Generated by Django 5.1.15 on 2026-08-30 20:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('sites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sensor_types', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('preprocessing', 'Preprocessing'), ('ready', 'Ready'), ('classifying', 'Classifying'), ('complete', 'Complete'), ('failed', 'Failed')], default='uploaded', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_sessions', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_sessions', to='accounts.organisation')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_sessions', to='sites.site')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='MineralZone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mineral_type', models.CharField(max_length=20)),
                ('confidence_score', models.PositiveSmallIntegerField(default=0)),
                ('estimated_depth_m', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('estimated_tonnage', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('status', models.CharField(choices=[('unconfirmed', 'Unconfirmed'), ('geologist_reviewed', 'Geologist Reviewed'), ('lab_confirmed', 'Lab Confirmed'), ('rejected', 'Rejected')], default='unconfirmed', max_length=20)),
                ('flagged_anomaly', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mineral_zones', to='accounts.organisation')),
                ('scan_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='scans.scansession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
