# Generated by Django 5.1.15 on 2026-08-30 20:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('traceability', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('origin_name', models.CharField(max_length=255)),
                ('origin_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('origin_lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('destination_name', models.CharField(max_length=255)),
                ('destination_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('destination_lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('driver', models.CharField(blank=True, max_length=255)),
                ('vehicle', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('loading', 'Loading'), ('in-transit', 'In Transit'), ('delayed', 'Delayed'), ('delivered', 'Delivered')], default='loading', max_length=12)),
                ('progress_pct', models.PositiveSmallIntegerField(default=0)),
                ('eta_hours', models.DecimalField(decimal_places=1, default=0, max_digits=6)),
                ('weight_kg', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gps_integrity', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='traceability.mineralbatch')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='accounts.organisation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
